image: kasproject/kas:0.13.0

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 1

stages:
- build
- deploy
# TODO: deploy artifacts to S3 and submit LAVA job

#build_bbb:
#  stage: build
#  script:
#    - /kas/docker-entrypoint
#    - gosu builder kas build --target core-image-minimal kas-bbb.yml

build_hihope-rzg2m:
  stage: build
  script:
    - /kas/docker-entrypoint
    - gosu builder kas build --target core-image-minimal kas-hihope-rzg2m.yml
  artifacts:
    paths:
      - build/tmp/deploy/images

deploy_hihope-rzg2m:
  stage: deploy
  script:
    - /kas/docker-entrypoint
    - scripts/deploy.sh buster \
      build/tmp/deploy/images/hihope-rzg2m/Image \
      build/tmp/deploy/images/hihope-rzg2m/core-image-minimal-hihope-rzg2m.tar.bz2

#build_qemuarm-ltp:
#  stage: build
#  script:
#    - /kas/docker-entrypoint
#    - gosu builder kas build --target core-image-minimal kas-qemuarm-ltp.yml

#build_qemuram64-ltp:
#  stage: build
#  script:
#    - /kas/docker-entrypoint
#    - gosu builder kas build --target core-image-minimal kas-qemuarm64-ltp.yml
