image: kasproject/kas:2.0

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 1

stages:
- build
- test

# TODO: Set `only` again to test jobs after the test flows are implemented

build_bbb:
  stage: build
  script:
    - kas build --target core-image-minimal kas-bbb.yml
  artifacts:
    paths:
      - build/tmp/deploy/images

test_bbb:
  stage: test
  script:
    - scripts/upload.sh bbb
      build/tmp/deploy/images/beaglebone/zImage
      build/tmp/deploy/images/beaglebone/core-image-minimal-beaglebone.cpio.gz
      build/tmp/deploy/images/beaglebone/am335x-boneblack.dtb
    - lava/submit-job.sh lava/jobs/bbb-uname.yml
  dependencies:
    - build_bbb

build_iwg20m:
  stage: build
  script:
    - kas build --target core-image-minimal kas-iwg20m.yml
  artifacts:
    paths:
      - build/tmp/deploy/images

test_iwg20m:
  stage: test
  script:
    - scripts/upload.sh iwg20m
      build/tmp/deploy/images/iwg20m/zImage
      build/tmp/deploy/images/iwg20m/core-image-minimal-iwg20m.tar.bz2
      build/tmp/deploy/images/iwg20m/r8a7743-iwg20d-q7.dtb
      build/tmp/deploy/images/iwg20m/r8a7743-iwg20d-q7-dbcm-ca.dtb
    - lava/submit-job.sh lava/jobs/iwg20m-uname.yml
  dependencies:
    - build_iwg20m

build_hihope-rzg2m:
  stage: build
  script:
    - kas build --target core-image-minimal kas-hihope-rzg2m.yml
  artifacts:
    paths:
      - build/tmp/deploy/images

test_hihope-rzg2m:
  stage: test
  script:
    - scripts/upload.sh hihope-rzg2m
      build/tmp/deploy/images/hihope-rzg2m/Image
      build/tmp/deploy/images/hihope-rzg2m/core-image-minimal-hihope-rzg2m.tar.bz2
      build/tmp/deploy/images/hihope-rzg2m/r8a774a1-hihope-rzg2m-ex.dtb
    - lava/submit-job.sh lava/jobs/hihope-rzg2m-uname.yml
  dependencies:
    - build_hihope-rzg2m

