image: kasproject/kas:2.0

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 1
  dtb: none
  build_image_name: core-image-minimal
  imgfmt: tar.bz2

stages:
- build
- test

# TODO: Set `only` again to test jobs after the test flows are implemented

.build_base:
  stage: build
  variables:
    upload_arg: "${target} ${bb_target} ${kernel} ${build_image_name}-${bb_target} ${imgfmt} ${dtb}"
  script:
    - kas build --target ${build_image_name} kas/board/${target}.yml
    - scripts/upload.sh ${upload_arg}

build:beaglebone-black:
  extends:
    - .build_base
  variables:
    target: beaglebone-black
    bb_target: beaglebone
    kernel: zImage
    dtb: am335x-boneblack.dtb
    imgfmt: cpio.gz

test:beaglebone-black:
  stage: test
  script:
    - lava/submit-job.sh beaglebone-black uname
  dependencies:
    - build:beaglebone-black

build:iwg20m:
  extends:
    - .build_base
  variables:
    target: iwg20m
    bb_target: iwg20m
    kernel: zImage
    dtb: r8a7743-iwg20d-q7.dtb

test:iwg20m:
  stage: test
  script:
    - lava/submit-job.sh r8a7743-iwg20d-q7 uname
  dependencies:
    - build:iwg20m

build:hihope-rzg2m:
  extends:
    - .build_base
  variables:
    target: hihope-rzg2m
    bb_target: hihope-rzg2m
    kernel: Image
    dtb: r8a774a1-hihope-rzg2m-ex.dtb

test:hihope-rzg2m:
  stage: test
  script:
    - lava/submit-job.sh r8a774a1-hihope-rzg2m-ex uname
  dependencies:
    - build:hihope-rzg2m

build:simatic-ipc227e:
  extends:
    - .build_base
  variables:
    target: simatic-ipc227e
    bb_target: simatic-ipc227e
    kernel: bzImage

test:simatic-ipc227e:
  stage: test
  script:
    # TODO: device_type name should be changed to "simatic-ipc227e"?
    - lava/submit-job.sh x86 uname
  dependencies:
    - build:simatic-ipc227e

build:de0-nano-soc:
  extends:
    - .build_base
  variables:
    target: de0-nano-soc
    bb_target: de0-nano-soc
    kernel: zImage
    dtb: socfpga_cyclone5_de0_nano_soc-de0-nano-soc.dtb

test:de0-nano-soc:
  stage: test
  script:
    - lava/submit-job.sh de0-nano-soc uname
  dependencies:
    - build:de0-nano-soc
