image: kasproject/kas:0.13.0

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 1

stages:
- build
#- deploy
# TODO: deploy artifacts to S3 and submit LAVA job

build_bbb:
  stage: build
  script:
    - /kas/docker-entrypoint
    - gosu builder kas build --target core-image-minimal kas-bbb.yml

build_hihope-rzg2m:
  stage: build
  script:
    - /kas/docker-entrypoint
    - gosu builder kas build --target core-image-minimal kas-hihope-rzg2m.yml

#build_qemuarm-ltp:
#  stage: build
#  script:
#    - /kas/docker-entrypoint
#    - gosu builder kas build --target core-image-minimal kas-qemuarm-ltp.yml

#build_qemuram64-ltp:
#  stage: build
#  script:
#    - /kas/docker-entrypoint
#    - gosu builder kas build --target core-image-minimal kas-qemuarm64-ltp.yml
