image: kasproject/kas:2.0

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: 1
  dtb: none
  feature_yaml: none
  imgname: none
  build_image_name: core-image-minimal
  kas_yaml: kas/board/${target}.yml
  imgfmt: tar.bz2

stages:
- build
- test

# TODO: Set `only` again to test jobs after the test flows are implemented

.build_base:
  stage: build
  script:
    - if [ "$feature_yaml" != "none" ]; then kas_yaml="${kas_yaml}:${feature_yaml}"; fi;
    - kas build --target ${build_image_name} ${kas_yaml}
    - if [ "$imgname" != "none" ]; then build_image_name="${build_image_name}-${imgname}"; fi;
    - scripts/upload.sh ${target} ${bb_target} ${kernel} ${build_image_name}-${bb_target} ${imgfmt} ${dtb}

.build_ltp:
  variables:
    feature_yaml: kas/opt/deby.yml:kas/opt/ltp.yml
    imgname: ltp

build:beaglebone-black:
  extends:
    - .build_base
  variables:
    target: beaglebone-black
    bb_target: beaglebone
    kernel: zImage
    dtb: am335x-boneblack.dtb
    imgfmt: cpio.gz

test:beaglebone-black:
  stage: test
  script:
    - lava/submit-job.sh beaglebone-black uname
  dependencies:
    - build:beaglebone-black

build:iwg20m:
  extends:
    - .build_base
  variables:
    target: iwg20m
    bb_target: iwg20m
    kernel: uImage
    dtb: r8a7743-iwg20d-q7.dtb

test:iwg20m:
  stage: test
  script:
    - lava/submit-job.sh r8a7743-iwg20d-q7 uname
  dependencies:
    - build:iwg20m

build:hihope-rzg2m:
  extends:
    - .build_base
  variables:
    target: hihope-rzg2m
    bb_target: hihope-rzg2m
    kernel: Image
    dtb: r8a774a1-hihope-rzg2m-ex.dtb

test:hihope-rzg2m:
  stage: test
  script:
    - lava/submit-job.sh r8a774a1-hihope-rzg2m-ex uname
  dependencies:
    - build:hihope-rzg2m

build:hihope-rzg2n:
  extends:
    - .build_base
  variables:
    target: hihope-rzg2n
    bb_target: hihope-rzg2n
    kernel: Image
    dtb: r8a774b1-hihope-rzg2n-ex.dtb

test:hihope-rzg2n:
  stage: test
  script:
    - lava/submit-job.sh r8a774b1-hihope-rzg2n-ex uname
  dependencies:
    - build:hihope-rzg2n

build:simatic-ipc227e:
  extends:
    - .build_base
  variables:
    target: simatic-ipc227e
    bb_target: simatic-ipc227e
    kernel: bzImage

test:simatic-ipc227e:
  stage: test
  script:
    # TODO: device_type name should be changed to "simatic-ipc227e"?
    - lava/submit-job.sh x86 uname
  dependencies:
    - build:simatic-ipc227e

build:de0-nano-soc:
  extends:
    - .build_base
  variables:
    target: de0-nano-soc
    bb_target: de0-nano-soc
    kernel: zImage
    dtb: socfpga_cyclone5_de0_nano_soc-de0-nano-soc.dtb

test:de0-nano-soc:
  stage: test
  script:
    - lava/submit-job.sh de0-nano-soc uname
  dependencies:
    - build:de0-nano-soc

build:r8a774c0-ek874:
  extends:
    - .build_base
  variables:
    target: r8a774c0-ek874
    bb_target: r8a774c0-ek874
    kernel: Image
    dtb: r8a774c0-ek874.dtb

test:r8a774c0-ek874:
  stage: test
  script:
    - lava/submit-job.sh r8a774c0-ek874 uname
  dependencies:
    - build:r8a774c0-ek874

build:zynqmp-zcu102:
  extends:
    - .build_base
  variables:
    target: zynqmp-zcu102
    bb_target: zynqmp-zcu102
    kernel: Image
    dtb: zynqmp-zcu102-rev1.0.dtb

test:zynqmp-zcu102:
  stage: test
  script:
    - lava/submit-job.sh zynqmp-zcu102 uname
  dependencies:
    - build:zynqmp-zcu102

# create image include ltp.

build:beaglebone-black-ltp:
  when: manual
  extends:
    - build:beaglebone-black
    - .build_ltp

build:iwg20m-ltp:
  when: manual
  extends:
    - build:iwg20m
    - .build_ltp

build:hihope-rzg2m-ltp:
  when: manual
  extends:
    - build:hihope-rzg2m
    - .build_ltp

build:hihope-rzg2n-ltp:
  when: manual
  extends:
    - build:hihope-rzg2n
    - .build_ltp

build:r8a774c0-ek874-ltp:
  when: manual
  extends:
    - build:r8a774c0-ek874
    - .build_ltp

build:simatic-ipc227e-ltp:
  when: manual
  extends:
    - build:simatic-ipc227e
    - .build_ltp

build:de0-nano-soc-ltp:
  when: manual
  extends:
    - build:de0-nano-soc
    - .build_ltp

build:zynqmp-zcu102-ltp:
  when: manual
  extends:
    - build:zynqmp-zcu102
    - .build_ltp
