FILESEXTRAPATHS_prepend := "${THISDIR}/files:"

# Kernel config is generated by defconfig + hihope-rzg2m.config
LINUX_DEFCONFIG = "defconfig"
SRC_URI_append = " file://hihope-rzg2m.config"

KERNEL_DEVICETREE = " \
    renesas/r8a774a1-hihope-rzg2m.dtb \
    renesas/r8a774a1-hihope-rzg2m-ex.dtb \
"
